[SPBU-21.B10] Task 2.1 Пономарев Николай
WoWaster/spbu_c_homeworks pull request #6
Opened 2021-09-24 17:45 UTC by WoWaster

Вывод от файла с GDrive: https://gist.github.com/WoWaster/153cf29c535da730a747fa1439a71c53

2021-09-26 09:43 UTC, ArtyomLobanov requested changes

2021-09-26 09:43 UTC, ArtyomLobanov commented on homework2/task_1.c
> +    char buffer[127] = "";
Что произойдёт, если в буффер из 127 элементов записать слово из 127 букв?

2021-09-26 09:43 UTC, ArtyomLobanov commented on homework2/task_1.c
> +        if (hasKey(map, buffer)) {
Фигурные скобки не по стайлгайду

2021-09-26 09:43 UTC, ArtyomLobanov commented on homework2/task_1.c
> +void generateCSVFromMap(LinkedMap* map, const char* filename)
Почему при чтении данных из файла вы передаёте дескриптор, а при записи – путь к файлу? Давайте внесём некоторое единообразие в работу с файлами. Скажем, принимайте всегда путь.

2021-09-26 09:43 UTC, ArtyomLobanov commented on homework2/task_1.c
> +    FILE* input = fopen(argv[1], "r");
А если пользователь передал нам некорретный путь?

2021-09-26 09:43 UTC, ArtyomLobanov commented on library/LinkedMap.c
> +    return false;
А нельзя ли как-то упростить эту конструкцию?
```cpp
if (flag) 
    return true;
return false;
```

2021-09-26 09:43 UTC, ArtyomLobanov commented on library/LinkedMap.c
> +    map->last = node;
Можно было добавлять новые вершины в начало списка. Тогда не нужно было бы хранить ссылку на хвост и в целом код немного проще был бы. Но ваш подход тоже имеет право на жизнь.

2021-09-26 09:43 UTC, ArtyomLobanov commented on library/LinkedMap.c
> +    }
Кстати, итерироваться можно и for-ом
```cpp
for (Node* current = map->first; current != NULL; current = current->nextElement) {
    ...
}
```

2021-09-26 09:44 UTC, ArtyomLobanov commented on library/LinkedMap.h
> +    struct Node* nextElement;
Либо просто в next

2021-09-26 14:37 UTC, WoWaster commented on library/LinkedMap.c
> +    }
В `if`-е мы не сравниваем с нулем, т.к. для компилятора `NULL == 0`. Но стоит ли использовать такое неявное сравнение в объявлении `for`? Например:
```c
for (Node* currentElement = map->first; currentElement; currentElement = currentElement->nextNode) {
        ...
}
``` 
?

2021-09-26 17:18 UTC, ArtyomLobanov commented on library/LinkedMap.c
> +    }
По выбранному стайлгайду – да. Не готов защищать эту позицию (мне тоже не всё в стайлгайде нравится), но единый стиль для проекта важнее индивидуальных предпочтений. А мы пытаемся по возможности приблизить процесс сдачи домашек к промышленной разработке.

2021-09-28 08:18 UTC, ArtyomLobanov requested changes

2021-09-28 08:18 UTC, ArtyomLobanov commented on library/LinkedMap.c
> +    return false;
А что изменилось-то? Почему просто flag не вернуть? По канону С любые отличные от 0 значения считаются истинными. true и false – просто define-ы для 1 и 0.

2021-10-01 15:20 UTC, ArtyomLobanov approved these changes
Ок, зачтено

2021-10-01 15:20 UTC, ArtyomLobanov commented on library/LinkedMap.c
> +        Node* node = getNode(map, key);
Тут, конечно, можно было один проход по списку сэкономить
```cpp
Node* node = getNode(map, key);
if (node) {
    node->value = value;
    return;
}
...
```

2021-10-01 15:20 UTC, merged